version: 2.1

orbs:
  node: circleci/node@3.0.0
  allure: ayte/allure@0.1.3

jobs:
  build:
    docker:
    - image: circleci/node:latest-browsers
    steps:
    - checkout
    - run:
        name: Allure archive download
        command: curl -L https://github.com/allure-framework/allure2/releases/download/2.13.1/allure-commandline-2.13.1.zip -o /tmp/allure.zip
    - run:
        name: Archive extraction
        command: unzip /tmp/allure.zip
    - run:
        name: Allure installation
        command: sudo mv allure-2.13.1 /usr/local/share/allure
    - run:
        name: Allure binary symlinking
        command: sudo ln -s /usr/local/share/allure/bin/allure /usr/local/bin/allure
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        command: npm ci
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run:
        command: npm run test
    - run:
        name: Allure report generation (allure-results -> allure-report)
        command: |
          allure generate --clean \
            --config /usr/local/share/allure/config/allure.yml \
            --report-dir allure-report \
            allure-results\
    - store_artifacts:
        path: allure-report
        destination: Report/Allure

workflows:
  workflow:
    jobs:
    - build

#previous version
# version: 2.0

# orbs:
#   node: circleci/node@3.0.0
#   allure: ayte/allure@0.1.3

# jobs:
#   allure-generate:
#     docker:
#       - image: circleci/openjdk:8
#     steps:
#       - allure/install
#       - allure/report
#     parallelism: 1

# workflows:
#   node-tests:   
#     jobs:
#       - node/test
#       - allure-generate:
#           requires:
#           - node/test
